### PR TITLE
building a heatmap of the Smashing magazine website

### PR DESCRIPTION
**Pull request by rubenpazch**
This project consists of building a heatmap of the Smashing magazine website

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @rubenpazch @phfdonda,
Your project looks good 👏👏, however, there are a few things that you need to fix.

- Below the navbar, the smashing website has 2  articles in 1 row, each takes half of the width.
Screenshot
- Yours has 2 articles but one has a larger width than the other.
Screenshot
**3 articles rows**
- [ ] It should contain 3 **articles**, **each takes one-third of the width.**, yours don't take a third of the width.

**Footer**
- [ ] Make sure it contains centered **links**, change them to links.

**Each article**
- [ ] Make sure all your articles use `<article>` tag [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/article_requirement.png), currently only a few use the tag, use it for the 1,2 or 3 articles per row sections

### Kindly make the suggested changes and request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

**Comment by phfdonda** [comment]
We have fixed all the problems mentioned and ask for another code review.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really great job team! :handshake: 
It has really come together and you have just one small detail to address. As @fatymahmed pointed out, the section beneath the header is to have a grid of 2 rows and two columns with equal-sized `div` containers at 50% width each. You currently have one row of 3 divs instead. 

Please look into this and make the appropriate changes, when that is done, please request another review! :100: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by phfdonda** [comment]
Hi, @Oluwadamilareolusakin, thank you for your review!
As my partner was talking with Fatima, she was seeing the Smashing Magazine website with a different resolution than we were. When seen in a resolution of about less than 2000px width, the media queries of the website kick in, and the three columns are substituted by two. 
However, the purpose of this project is not to create a responsive webpage. If someone with even greater resolution than ours would check the original page to code review our project, it would present 4 columns side-by-side, while in ours show 3, and in Fatima's show 2. Since we can't know what is going to be the resolution of the reviewer, and this is not a project about responsiveness, it is impossible for us to make these changes. Therefore, it is not a problem with our design, and that can't be fixed. To properly access the assignment, you must change the resolution to match the one presented (with three columns).

2-col
3-col
4-col



Thank you for your review and support! =)

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Comment by nikasulo** [comment]
Hello @phfdonda, I appreciate and understand your comoments.  However, please note that what myself and @fatymahmed have pointed out to you are hard requirements and as such they are mandatory. If the changes aren't made I don't see you getting an approval regardless of how nice the project looks. Kindly reconsider your position on the matter. Thank you! :smile:

**Comment by phfdonda** [comment]
> Hello @phfdonda, I appreciate and understand your comoments. However, please note that what myself and @fatymahmed have pointed out to you are hard requirements and as such they are mandatory. If the changes aren't made I don't see you getting an approval regardless of how nice the project looks. Kindly reconsider your position on the matter. Thank you!

Hi, @Oluwadamilareolusakin, thank you for you quick answer.
Could you please direct me to these requirements? I can seem to find them, neither in the Odin Project page, neither on Microverse's page. I would not like to keep committing errors, reading the wrong requirements. Thank you a lot!

**Comment by nikasulo** [comment]
Hello again :smile:, I will grab you a screenshot and send to you on the Slack. One moment.

**Comment by phfdonda** [comment]
> Hello again 😄, I will grab you a screenshot and send to you on the Slack. One moment.

Ok, thank you! I'll be waiting!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @rubenpazch     
#### Great Job so far, but there are a few more things required. 
### Page Structure
 - [ ] This section should  2 articles, each takes half of the width 


 - [ ] This section should contains 3 articles, each takes one-third of the width 


 - [ ] This section should  contains 1 article, which takes the full width 



### Make changes and submit another code review request.
*Happy coding*

**Comment by phfdonda** [comment]
We have made all the changes required and request a new code review.

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team!
### Nice job! Project looks! :+1: 

But you still need to fix next and your project can be approved:


* Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. (Students were asked to use this one, so in most cases their code should be already validated) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
screen

validator


* Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history
screen

* I hope this article can help you [HTML Headings](https://www.w3schools.com/html/html_headings.asp)
### Please kindly fix the above issues and send another code review request.
* If you have any questions or need help, you can message me on slack (@ Anna Muzykina). Happy coding

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved ✈️ 

Hi Team, Congratulations on fixing all the requested changes by previous reviewers. I will have to approve your project 🍷 . Go ahead and merge to master and submit project completion form. 🙂 

Happy coding 💻 
Daniel Larbi Addo

**Pull request merged**
